# Generated by Django 2.1.5 on 2019-03-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190329_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='user name'),
        ),
    ]
