# Generated by Django 2.1.5 on 2019-03-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190329_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='userss', max_length=20, verbose_name='user name'),
        ),
    ]
