# Generated by Django 2.1.5 on 2019-04-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgForSchool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='date_start',
            field=models.DateField(verbose_name='date_start'),
        ),
    ]
