# Generated by Django 2.1.5 on 2019-04-16 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MgForSchool', '0003_auto_20190404_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrecord',
            name='date_last',
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='开始日期'),
        ),
    ]
