# Generated by Django 2.1.5 on 2019-04-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgForSchool', '0004_auto_20190416_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='SOM',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='订单金额'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订单时间'),
        ),
    ]
