# Generated by Django 2.1.5 on 2019-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgForSchool', '0006_auto_20190417_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='is_val',
            field=models.BooleanField(default=True, verbose_name='is_valid'),
        ),
    ]
