# Generated by Django 2.1.5 on 2019-04-17 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MgForSchool', '0007_auto_20190417_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始日期'),
        ),
    ]
