# Generated by Django 2.1.5 on 2019-04-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgForSchool', '0008_auto_20190417_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='date_last',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='订购时长'),
        ),
    ]
