# Generated by Django 2.1.5 on 2019-05-05 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MgForSchool', '0009_orderrecord_date_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionId', models.CharField(default='unknownComp', max_length=32, verbose_name='赛事')),
                ('eventId', models.CharField(default='unknownEvent', max_length=6, verbose_name='项目')),
                ('roundTypeId', models.CharField(default='unknownRound', max_length=1, verbose_name='轮次')),
                ('pos', models.SmallIntegerField(default=0, verbose_name='排名')),
                ('best', models.IntegerField(default='-1', verbose_name='最好成绩')),
                ('average', models.IntegerField(default='-2', verbose_name='平均成绩')),
                ('value1', models.IntegerField(default='-2', verbose_name='第一次复原')),
                ('value2', models.IntegerField(default='-2', verbose_name='第二次复原')),
                ('value3', models.IntegerField(default='-2', verbose_name='第三次复原')),
                ('value4', models.IntegerField(default='-2', verbose_name='第四次复原')),
                ('value5', models.IntegerField(default='-2', verbose_name='第五次复原')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NPresults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
