# Generated by Django 2.1.5 on 2019-05-05 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MgForSchool', '0012_auto_20190505_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nresaults',
            new_name='Nresault',
        ),
    ]
