# Generated by Django 2.1.5 on 2019-05-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MgForSchool', '0014_orderrecord_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrecord',
            name='location',
            field=models.CharField(default='XX', max_length=25, verbose_name='订单使用位置'),
        ),
    ]
